

%% Load strings
strings = {...
    'How does a penguin keep its house together?', 'Igloos it.',...
    'I heard there is a store called Moderation.', 'They have everything there.', ...
    'A steak pun?', '...that is a rare medium well done.',...
    'How can you tell an ant is a boy or a girl?', 'They are all girls, otherwise they would be called uncles.',...
    'What password does Forest Gump use?', '1forrest1',...
    'I do not play soccer competitively.', 'I only play for kicks.',...
    'I used to work in a shoe recyling centre.', 'It was sole destroying.',...
    'What was it like when the two antennas got married?', 'I heard the ceremony was boring, but the reception was great.',...
    'How do you organise an outer-space party?', 'You planet.',...
    'Things for my uncle took a turn for the worst when he covered his back in lard.', 'I mean, he really went downhill fast.',...
    'Never trust an atom.', 'They make up everything.',...
    'Thanks for explaining the word *many* to me.', 'It means a lot.',...
    'How do you date a nurse?', 'Be patient.',...
    'I bought some shoes from a drug dealer.', 'I have been tripping all day.',...
    'What do you call a priest who becomes a lawyer?', 'A father in law.',...
    'My boyfriend told me he wanted to leave me because I always pretend to be a transformer.',...
    'I told him no! I can change!',...
    'I bought a new pair of gloves today. They were both lefts.',...
    'On the one hand, that is fine, but on the other it is just not right.',...
    'I burned 2,000 calories today!', 'That is what I get for forgetting about the brownies I had in the oven.',...
    'R.I.P. boiled water.', 'You will be mist.',...
    'The future, the present, and the past walked into a bar.', 'Things got really tense.',...
    'Online shopping is terrible.', 'I tried to buy a lighter and only found 13,876 matches',...
    'My friend always wants me to blow air on him when he is too warm.', 'Honestly, Im not a fan.',...
    'To the mathmematicians who thought of zero...', '...thanks for nothing.',...
    'A salesperson came to my door selling burial plots.', 'I thought, this is the last thing I need.',...
    'Atheism?', 'I heard it is not-for-prophet',...
    'What is the best thing about living in Switzerland?', 'Well, the flag is a big plus.',...
    'My girlfriend told me I think too much like a detective, and that we should split up.',...
    'I said that is a good idea, that way we can cover more ground.',...
    'I was addicted to soap.', 'Good thing I am clean now.',...
    'E.T. got home.', 'His mum asked: Where on Earth have you been?',...
    'I am in fact a really bad electrician.', 'Most people are shocked when they find out.',...
    'Guardians of the Galaxy', 'Otherwise known as security outside of the Samsung store.',...
    'I heard a child psychic broke out of jail.', 'A small medium is at large.',...
    'I handed my husband a gluestick instead of chapstick.', 'He still is not talking to me',...
    'I got a neck brace back in 2009.', 'Have never looked back.',...
    'Did you hear about the kidnapping?', 'No worries, the little guy woke up eventually.',...
    'A termite walks into a bar.', 'It asked where is the bar tender.',...
    'I courtroom artist was arrested today.', 'The details are sketchy.',...
    'I did not bother me when someone threw a fizzy drink at my aead.', 'It was a soft drink.',...
    'My dog has a bad habit of chasing people in cars.', 'I have since told my dog to stop stealing vehicles.',...
    'I wrote a ballad about tortillas.', 'Well, it was more of a rap.',...
    'With great reflexes...', 'Comes great response ability.',...
    'I told my class to write, but their pencils were broken.', 'They told me the lesson was pointless.',...
    'Why do aliens avoid our planet?', 'Terrible ratings. One star.',...
    'Possible profession: window cleaning.', 'It is something I can definitely see myself doing.'...
    };
numberOfBits = 5;
bitCount = 0;
if i == 1; bitShift = 1; sure = 0; skip = 0; end

%% Display
Screen('Flip', window);
Screen('DrawText', window,...
    'Do you want to see dad jokes? "Yes" <-- --> "No"', 100, yCenter, white);
Screen('Flip', window); WaitSecs(.01);
[keyIsDown,secs, keyCode] = KbPass({'RightArrow', 'LeftArrow'});

if keyCode(KbName('RightArrow')) && sure == 0
    sure = 1;
    Screen('DrawText', window,...
        'Are you sure? "Yes" <-- --> "No"', 100, yCenter, white);
    Screen('Flip', window); WaitSecs(.1);
    
    [keyIsDown,secs, keyCode] = KbPass({'RightArrow', 'LeftArrow'});
    
    if keyCode(KbName('LeftArrow'))
        Screen('DrawText', window,...
            ['You are SURE?', 'I thought your name was ', Name, '!?'], 100, yCenter, white);
        Screen('Flip', window); WaitSecs(.01);
    end
    
    [keyIsDown,secs, keyCode] = KbPass
    WaitSecs(.1);
    
    Screen('DrawText', window,...
        'So do you want to see dad jokes or not? "Yes" <-- --> "No"', 100, yCenter, white);
    Screen('Flip', window); WaitSecs(.01);
    
    
    [keyIsDown,secs, keyCode] = KbPass({'RightArrow', 'LeftArrow'});
    WaitSecs(.1);
    
    
    if keyCode(KbName('RightArrow'))
        Screen('DrawText', window,':(', 100, yCenter, white);
        Screen('Flip', window); WaitSecs(.01);
        KbPass(); skip = 1;
    end
    
elseif keyCode(KbName('RightArrow')) && sure == 1
    skip = 1;
end


if skip == 0
    Screen('DrawText', window,...
        ':)', 100, yCenter, white);
    Screen('Flip', window); WaitSecs(.01);
    [keyIsDown,secs, keyCode] = KbCheck;
    while  ~keyCode(KbName('LeftArrow')) && ~keyCode(KbName('RightArrow'))
        [keyIsDown,secs, keyCode] = KbCheck; WaitSecs(.001); end
    WaitSecs(.5);
    if keyCode(KbName('LeftArrow'))
        while bitCount < numberOfBits*2
            for lolz = 1:2
                if lolz == 1
                    Screen('DrawText', window,...
                        char(strings(bitShift)), 100, yCenter-150, white);
                elseif lolz == 2
                    Screen('DrawText', window,...
                        char(strings(bitShift)), 100, yCenter, white);
                end
                bitShift = bitShift + 1;
                bitCount = bitCount + 1;
                [keyIsDown,secs, keyCode] = KbCheck;
                while  ~keyCode; [keyIsDown,secs, keyCode] = KbCheck;...
                        WaitSecs(.001); end
                if  keyCode(KbName('DownArrow')); break; end
                Screen('Flip', window);
                if lolz == 2; WaitSecs(.75);
                elseif lolz == 1; WaitSecs(.5); end
            end
            if  keyCode(KbName('DownArrow'))...
                    && lolz == 2; Screen('Flip', window); ...
                    break; end
            %Screen('Flip', window);
        end
    end
elseif skip == 1
    skip = 0;
end



%% Wipe

strings = [];






